kind: Deployment
apiVersion: apps/v1
metadata:
  name: qotd-web
  namespace: qotd
  labels:
    app: qotd
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotd-web
  template:
    metadata:
      labels:
        app: qotd-web
    spec:
      volumes:
        - name: settings
          configMap:
            name: qotd-web-factory-settings
      restartPolicy: Always
      containers:
        - name: qotd-web
          image: registry.gitlab.com/quote-of-the-day/qotd-web:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: settings
              mountPath: /app/data
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: svc
              containerPort: 8080
              protocol: TCP
          env:
            - name: LOCAL_LOGGING
              value: "false"
            - name: ENABLE_INSTANA
              value: "true"
            - name: QUOTE_SVC
              value: "qotd-quote.qotd.svc.cluster.local:3001"
            - name: AUTHOR_SVC
              value: "qotd-author.qotd.svc.cluster.local:3002"
            - name: RATING_SVC
              value: "qotd-rating.qotd.svc.cluster.local:3004"
            - name: PDF_SVC
              value: "qotd-pdf.qotd.svc.cluster.local:3005"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: "50m"
              memory: "40Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: qotd-web-factory-settings
  namespace: qotd
  labels:
    app: qotd
    tier: web
data:
  factory_settings.json: |-
    {
        "api": {"mean": 100, "stdev": 200, "min":10,"max":500},
        "cpu": {"mean": 0.5, "stdev": 0.5, "min":0.03,"max":1},
        "mem": {"mean": 2648570, "stdev": 250000, "min":104857, "max":4718592}
    }
---
apiVersion: v1
kind: Service
metadata:
  name: qotd-web
  labels:
    app: qotd
    tier: web
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: qotd-web
---
apiVersion: v1
kind: Service
metadata:
  name: qotd-web-svc
  labels:
    app: qotd
    tier: web
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: svc
  selector:
    app: qotd-web
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: qotd-web
  labels:
    app: qotd
    tier: web
spec:
  subdomain: ''
  to:
    kind: Service
    name: qotd-web
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None


